services:
  - type: web
    name: ethio-crop-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    workingDirectory: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TF_USE_LEGACY_KERAS
        value: 0
